#!/bin/sh
#./enable-compression
rsync -av --delete --delete-excluded --exclude '*~' --exclude /node_modules --exclude /server ~/Projects/Mahjong/mahjong-pwa/ elf021@elf021.pairserver.com:public_html/mahjong/
