* mahjong to do list
[x] put the game number into the url
	the proposition is that the web app can be launched
	with a url that specifies the game to be played as
	a parameter in https://mahjong.elf.org#gameIdentifier
	a decimal number is a gameIndentifier as an int
	a hexadecimal number is a gameIdentifier as an int
	an arbitrary string is a gameIdentifier which is hashed to an int
	the int, possibly masked to its lower bits, is used as a seed for 
	the game random number generator.
   
	this means that clicking a url with a gameIdentifier will take you
	to the web app to play the specified game.

	don't put the game number in the url, 
[x] get the launch url out of the game for sharing
	I guess it follows that you need to be able to get to the game id
	of the game you're playing, either by copying the url as a selection
	or by popping out to a browser hosted window with url controls.
[ ] stop the bogus focus
	I get keyboard focus frames on tiles that aren't playable, perhaps
	an onFocus handler could check the tile playability and blur if
	not appropriate.
[ ] look for spurious clicks
	may not be able to detect this without console logging the click
	handlers.  I got a select click on the menubutton once.
[x] fix the flash of wrong color on load.
	It was a wrong color in the manifest.json
[x] make it prettier
	the icons are a little too brutalist for the rest of the game.
	I need mahjong themed av control buttons to go with the mahjong
	themed tiles
	so the icons could be displayed on mahjong tile buttons
	Oh, use the ideographic 3 as the hamburger menu button, and then
	redo the av controls as brush drawn symbols!
[x] get a different undo button
[x] get a copy url to clipboard button
[x] make the toplevel menu switch between horizonal and vertical presentation
	depending on screen orientation.
[-] add box outline to the menu frame?
[x] lose box outline on the finish dialogs?
[-] add box outlines to the icon buttons?
[-] add hover/activation eye candy to the icon buttons?
[x] get a better presentation of the discard order options
[ ] reinstate the no discard discard order option
[?] cancel the menu with stray taps outside the menu area
[x] remove the end of game testing menu options.
[x] reduce the autozoom activity
	rewrite the viewbox meta item in index.html
	said 1-5 zoom, initial 1, made it 1-2 zoom initial 1.
	Didn't make that much difference, it may be advisory.
[x] convert the menu into a toolbar
[x] the discard by play order display appears to be wrapping in some 
	situations.  Ah, it was the NSEW remapping being applied to
	the discard by play order pile.
[x] save the current play state to disk, restore on restart
	this consists of the game number, the discardArrange state,
	and the discarded tile indexes.  Interacts with the url hash.
	Only saving the gameNumber for now.
[ ] save the history, a list of game numbers played and the results of the games.
[x] the menu was hidden beneath the discard pile
[ ] safari doesn't show hash in navigation bar url, but appears to apply it
[x] refresh appears to advance the hash in chrome, random jump.
[ ] end of game dialog not centering, not wide enough for all icon buttons
[ ] one aligns and one doesn't?
[ ] is the discard order being saved and restored?
[ ] ipad not displaying any icon for installed app
[ ] ipad tool bar conflicts with ipad system notifications
